const CARD_CONTENTS = {
    "cards": [
        {
            "question": "What is the typical color of maple leaves in the fall?",
            "answer1": "Crimson red",
            "answer2": "Bright green",
            "correct_idx": 0,
        },
        {
            "question": "Which fruit is commonly associated with fall and used in pies?",
            "answer1": "Pumpkin",
            "answer2": "Watermelon",
            "correct_idx": 1,
        },
        {
            "question": "What is the term for the practice of collecting and carving pumpkins in the fall?",
            "answer1": "Pumpkin carving",
            "answer2": "Watermelon sculpting",
            "correct_idx": 0,
        },
        {
            "question": "What holiday is celebrated on the last Thursday of November in the United States?",
            "answer1": "Halloween",
            "answer2": "Thanksgiving",
            "correct_idx": 1,
        },
        {
            "question": "In which season do leaves typically change color and fall from trees?",
            "answer1": "Spring",
            "answer2": "Autumn",
            "correct_idx": 1,
        },
        {
            "question": "Which spice is commonly used in fall-flavored beverages like pumpkin spice lattes?",
            "answer1": "Cinnamon",
            "answer2": "Mustard",
            "correct_idx": 0,
        },
        {
            "question": "What do people traditionally bob for on Halloween?",
            "answer1": "Potatoes",
            "answer2": "Apples",
            "correct_idx": 1,
        },
        {
            "question": "What is the primary color of corn mazes often found in fall festivals?",
            "answer1": "Yellow",
            "answer2": "Blue",
            "correct_idx": 0,
        },
        {
            "question": "Which holiday involves dressing up in costumes and going door-to-door for candy?",
            "answer1": "Halloween",
            "answer2": "Valentine's Day",
            "correct_idx": 0,
        },
        {
            "question": "What is the primary ingredient in a classic Thanksgiving dish called 'stuffing'?",
            "answer1": "Bread",
            "answer2": "Pasta",
            "correct_idx": 0,
        },
        {
            "question": "What do you call the large, round, orange fruit often used for Halloween decorations?",
            "answer1": "Cabbage",
            "answer2": "Pumpkin",
            "correct_idx": 1,
        },
        {
            "question": "Which season follows summer and precedes winter?",
            "answer1": "Spring",
            "answer2": "Autumn",
            "correct_idx": 1,
        },
        {
            "question": "What do you call the warm, spiced beverage often served at fall gatherings?",
            "answer1": "Apple cider",
            "answer2": "Lemonade",
            "correct_idx": 0,
        },
        {
            "question": "In the United States, which holiday is celebrated on the fourth Thursday of November?",
            "answer1": "Thanksgiving",
            "answer2": "Easter",
            "correct_idx": 0,
        },
        {
            "question": "What is the process of leaves changing color in the fall due to reduced daylight hours called?",
            "answer1": "Senescence",
            "answer2": "Photosynthesis",
            "correct_idx": 0,
        },
        {
            "question": "What do people typically carve into pumpkins for Halloween decorations?",
            "answer1": "Sudoku puzzles",
            "answer2": "Jack-o'-lantern faces",
            "correct_idx": 1,
        },
        {
            "question": "Which tree species is known for its vibrant red leaves in the fall?",
            "answer1": "Palm",
            "answer2": "Maple",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the activity where you jump into a pile of fallen leaves?",
            "answer1": "Leaf pile jumping",
            "answer2": "Mud wrestling",
            "correct_idx": 0,
        },
        {
            "question": "What is the first day of the fall season called?",
            "answer1": "Autumnal equinox",
            "answer2": "Winter solstice",
            "correct_idx": 0,
        },
        {
            "question": "What is the popular fall spice blend used in pies and lattes, consisting of cinnamon, nutmeg, and cloves?",
            "answer1": "Taco Seasoning",
            "answer2": "Pumpkin spice",
            "correct_idx": 1,
        },
        {
            "question": "What is the traditional bird often served as the centerpiece of a Thanksgiving meal?",
            "answer1": "Duck",
            "answer2": "Turkey",
            "correct_idx": 1,
        },
        {
            "question": "Which spice is a key ingredient in pumpkin spice lattes and many fall desserts?",
            "answer1": "Cinnamon",
            "answer2": "Garlic",
            "correct_idx": 0,
        },
        {
            "question": "What do people typically carve into pumpkins for Halloween decorations?",
            "answer1": "Jack-o'-lantern faces",
            "answer2": "Sudoku puzzles",
            "correct_idx": 0,
        },
        {
            "question": "Which fruit is often used in traditional fall pies, such as apple and pumpkin pies?",
            "answer1": "Bananas",
            "answer2": "Apples",
            "correct_idx": 1,
        },
        {
            "question": "What holiday is celebrated on the last Thursday of November in the United States?",
            "answer1": "Easter",
            "answer2": "Thanksgiving",
            "correct_idx": 1,
        },
        {
            "question": "What do you call the process of leaves changing colors and falling from trees in the fall?",
            "answer1": "Autumnal leaf drop",
            "answer2": "Summer bloom",
            "correct_idx": 0,
        },
        {
            "question": "What is the term for the decorative arrangement of leaves, pinecones, and other fall items often placed on tables?",
            "answer1": "Frisbee",
            "answer2": "Centerpiece",
            "correct_idx": 0,
        },
        {
            "question": "What is the main ingredient in a classic fall soup known as butternut squash soup?",
            "answer1": "Pineapple",
            "answer2": "Butternut squash",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the practice where kids dress up in costumes and go door-to-door for candy on Halloween?",
            "answer1": "Trick-or-treating",
            "answer2": "Math tutoring",
            "correct_idx": 0,
        },
        {
            "question": "In the United States, what is the holiday celebrated on the fourth Thursday of November, often featuring a big feast?",
            "answer1": "Valentine's Day",
            "answer2": "Thanksgiving",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the long weekend marking the end of summer and the beginning of fall in the U.S.?",
            "answer1": "Labor Day",
            "answer2": "Groundhog Day",
            "correct_idx": 0,
        },
        {
            "question": "What is the term for the custom of collecting apples by biting into them while they're suspended on a string?",
            "answer1": "Soccer practice",
            "answer2": "Bobbing for apples",
            "correct_idx": 1,
        },
        {
            "question": "What type of tree is known for its bright red leaves in the fall and is often used in landscaping?",
            "answer1": "Maple",
            "answer2": "Palm",
            "correct_idx": 0,
        },
        {
            "question": "What is the seasonal drink made from crushed and fermented grapes that is popular in the fall?",
            "answer1": "lemonade",
            "answer2": "Wine",
            "correct_idx": 1,
        },
        {
            "question": "What is the holiday that celebrates and honors those who have served in the military, occurring in November?",
            "answer1": "Veterans Day",
            "answer2": "April Fools' Day",
            "correct_idx": 0,
        },
        {
            "question": "What is the name of the activity where you jump into a pile of fallen leaves for fun?",
            "answer1": "Leaf pile jumping",
            "answer2": "Snowball fight",
            "correct_idx": 0,
        },
        {
            "question": "What is the holiday that falls on October 31st and involves costumes and trick-or-treating?",
            "answer1": "Christmas",
            "answer2": "Halloween",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the festival celebrated in late September to early October in Germany, known for its beer and pretzels?",
            "answer1": "Pancake Day",
            "answer2": "Oktoberfest",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the annual celestial event that occurs in October, producing streaks of light in the night sky?",
            "answer1": "Lunar Eclipse",
            "answer2": "Meteor shower",
            "correct_idx": 1,
        },
        {
            "question": "What is the term for the practice of preserving fruits and vegetables in jars to enjoy during the winter months?",
            "answer1": "Canning",
            "answer2": "Playing chess",
            "correct_idx": 0,
        },
        {
            "question": "What is the term for the process by which trees shed their leaves in the fall?",
            "answer1": "Autumnal defoliation",
            "answer2": "Spring blossoming",
            "correct_idx": 0,
        },
        {
            "question": "Which spice is commonly used in fall desserts like pumpkin pie and apple cider?",
            "answer1": "Black pepper",
            "answer2": "Cinnamon",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the harvest festival celebrated in the United States and Canada?",
            "answer1": "Harvest Day",
            "answer2": "Thanksgiving",
            "correct_idx": 1,
        },
        {
            "question": "Which fruit is often associated with a bobbing game played during Halloween?",
            "answer1": "Pear",
            "answer2": "Apple",
            "correct_idx": 1,
        },
        {
            "question": "What do you call a period of warmer weather in the fall, also known as Indian summer?",
            "answer1": "Arctic blast",
            "answer2": "Warm spell",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the phenomenon where the moon appears larger and brighter in the fall?",
            "answer1": "Harvest moon",
            "answer2": "Blue moon",
            "correct_idx": 0,
        },
        {
            "question": "What type of farms are popular destinations for families in the fall, offering activities like corn mazes and pumpkin picking?",
            "answer1": "Farms",
            "answer2": "Factories",
            "correct_idx": 0,
        },
        {
            "question": "Which woodland creature is known for gathering and storing nuts in the fall for winter food?",
            "answer1": "Raccoon",
            "answer2": "Squirrel",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the warm, spiced beverage often enjoyed during fall, made from apple juice and spices?",
            "answer1": "Cold water",
            "answer2": "Hot cider",
            "correct_idx": 1,
        },
        {
            "question": "What do you call the colorful foliage of deciduous trees in the fall?",
            "answer1": "Fall foliage",
            "answer2": "Winter branches",
            "correct_idx": 0,
        },
        {
            "question": "Which holiday, celebrated on October 31st, involves costumes, trick-or-treating, and haunted houses?",
            "answer1": "Halloween",
            "answer2": "Easter",
            "correct_idx": 0,
        },
        {
            "question": "What is the name of the seasonal dessert made by rolling sponge cake around a sweet filling, often flavored with pumpkin or spices?",
            "answer1": "Chocolate bar",
            "answer2": "Pumpkin roll",
            "correct_idx": 1,
        },
        {
            "question": "Which vegetable is commonly roasted, mashed, or used in soups during fall, especially for Thanksgiving dinners?",
            "answer1": "Cucumber",
            "answer2": "Potato",
            "correct_idx": 1,
        },
        {
            "question": "What do you call the crisp, cool air and clear blue skies typical of fall days?",
            "answer1": "Autumn breeze",
            "answer2": "Summer haze",
            "correct_idx": 0,
        },
        {
            "question": "Which fall holiday is known for the custom of lighting lanterns and the symbol of a glowing, carved pumpkin?",
            "answer1": "Halloween",
            "answer2": "Valentine's Day",
            "correct_idx": 0,
        },
        {
            "question": "What type of pie, often served in the fall, is made from a variety of fruits such as apples, berries, or peaches?",
            "answer1": "Fruit pie",
            "answer2": "Pizza pie",
            "correct_idx": 0,
        },
        {
            "question": "What is the name of the harvest festival celebrated in Germany, featuring traditional foods, music, and dancing?",
            "answer1": "Oktoberfest",
            "answer2": "Winterfest",
            "correct_idx": 0,
        },
        {
            "question": "Which famous author wrote the novel 'The Legend of Sleepy Hollow,' a Halloween classic?",
            "answer1": "Jane Austen",
            "answer2": "Washington Irving",
            "correct_idx": 1,
        },
        {
            "question": "What is the term for the brightly colored leaves that fall from trees, covering the ground in the fall?",
            "answer1": "Leaf litter",
            "answer2": "Snowflakes",
            "correct_idx": 0,
        },
        {
            "question": "Which spice, derived from the bark of trees, is commonly used in fall recipes and gives a warm, sweet flavor?",
            "answer1": "Chili powder",
            "answer2": "Nutmeg",
            "correct_idx": 0,
        },
        {
            "question": "What is the term for the practice of collecting and carving pumpkins in the fall?",
            "answer1": "Pumpkin carving",
            "answer2": "Watermelon sculpting",
            "correct_idx": 0,
        },
        {
            "question": "What is the primary color of corn mazes often found in fall festivals?",
            "answer1": "Blue",
            "answer2": "Yellow",
            "correct_idx": 1,
        },
        {
            "question": "What do people traditionally bob for on Halloween?",
            "answer1": "Apples",
            "answer2": "Potatoes",
            "correct_idx": 0,
        },
        {
            "question": "What is the primary ingredient in a classic Thanksgiving dish called 'stuffing'?",
            "answer1": "Pasta",
            "answer2": "Bread",
            "correct_idx": 1,
        },
        {
            "question": "What do you call the warm, spiced beverage often served at fall gatherings?",
            "answer1": "Lemonade",
            "answer2": "Apple cider",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the activity where you jump into a pile of fallen leaves?",
            "answer1": "Leaf pile jumping",
            "answer2": "Mud wrestling",
            "correct_idx": 0,
        },
        {
            "question": "What is the first day of the fall season called?",
            "answer1": "Autumnal equinox",
            "answer2": "Winter solstice",
            "correct_idx": 0,
        },
        {
            "question": "What is the popular fall spice blend used in pies and lattes, consisting of cinnamon, nutmeg, and cloves?",
            "answer1": "Taco seasoning",
            "answer2": "Pumpkin spice",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the seasonal beverage made from fermented apple juice, popular in the fall?",
            "answer1": "Orange juice",
            "answer2": "Cider",
            "correct_idx": 1,
        },
        {
            "question": "What's the common name for the fall holiday that falls on October 31st and involves costumes and trick-or-treating?",
            "answer1": "Christmas",
            "answer2": "Halloween",
            "correct_idx": 1,
        },
        {
            "question": "What is the main protein typically served at a traditional Thanksgiving dinner?",
            "answer1": "Turkey",
            "answer2": "Tofu",
            "correct_idx": 0,
        },
        {
            "question": "What is the holiday that occurs on the fourth Thursday of November and involves a feast of gratitude?",
            "answer1": "Thanksgiving",
            "answer2": "New Year's Day",
            "correct_idx": 0,
        },
        {
            "question": "What is the name of the spice that is often used in fall desserts and drinks, like pumpkin pie?",
            "answer1": "Paprika",
            "answer2": "Cinamonn",
            "correct_idx": 1,
        },
        {
            "question": "What is the term for the event where you gather and pile up leaves to create a jumping point?",
            "answer1": "Leaf pile",
            "answer2": "Marshmallow pit",
            "correct_idx": 0,
        },
        {
            "question": "What is the holiday that celebrates and honors those who have served in the military, occurring in November?",
            "answer1": "April Fools' Day",
            "answer2": "Veterans day",
            "correct_idx": 1,
        },
        {
            "question": "What is the name of the vibrant meteor shower that usually occurs in the fall?",
            "answer1": "Snowflakes",
            "answer2": "Orionids",
            "correct_idx": 1,
        },
        {
            "question": "Which outdoor activity is commonly enjoyed in the fall, involving hitting a ball into a series of holes on a course?",
            "answer1": "Golf",
            "answer2": "Surfing",
            "correct_idx": 0,
        },
        {
            "question": "What is the primary color associated with the changing leaves during the fall season?",
            "answer1": "Neon green",
            "answer2": "Red",
            "correct_idx": 1,
        },
        {
            "question": "What's the term for the practice where people dress up as monsters and go door-to-door asking for candy on October 31st?",
            "answer1": "Grocery shopping",
            "answer2": "Trick-or-treating",
            "correct_idx": 1,
        },
        {
            "question": "What is the process by which some animals prepare for the fall and winter by storing food and getting ready for hibernation?",
            "answer1": "Sunbathing",
            "answer2": "Migration",
            "correct_idx": 1,
        },
    ]
}
